AUX_SOURCE_DIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}
  SRCS)

ADD_EXECUTABLE(tv-key ${SRCS})

SET_TARGET_PROPERTIES(tv-key
  PROPERTIES COMPILE_FLAGS "-fPIE")
SET_TARGET_PROPERTIES(tv-key
  PROPERTIES LINK_FLAGS "-pie")

SET(INSTALL_DIR
  "/opt/usr/share/tizen-tools/cli/tv-key")

INSTALL(TARGETS tv-key
  DESTINATION ${INSTALL_DIR})
INSTALL(FILES "${CMAKE_CURRENT_SOURCE_DIR}/tool.md"
  DESTINATION ${INSTALL_DIR})
