AUX_SOURCE_DIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}
  SRCS)

ADD_EXECUTABLE(tv-screenshot ${SRCS})

SET_TARGET_PROPERTIES(tv-screenshot
  PROPERTIES COMPILE_FLAGS "-fPIE")
SET_TARGET_PROPERTIES(tv-screenshot
  PROPERTIES LINK_FLAGS "-pie")

SET(INSTALL_DIR
  "/opt/usr/share/tizen-tools/cli/tv-screenshot")

INSTALL(TARGETS tv-screenshot
  DESTINATION ${INSTALL_DIR})
INSTALL(FILES "${CMAKE_CURRENT_SOURCE_DIR}/tool.md"
  DESTINATION ${INSTALL_DIR})
